### ISSUE TITLE
Upper limit for flexiplex_filter

### ISSUE THREAD

**Issue by nadiadavidson** [DavidsonGroup/flexiplex#24]
@olliecheng First instance of the filter selecting the wrong rank. See figures below. First in default setting, second is shifting the upper limit to 12000.

![Figure_1](https://github.com/DavidsonGroup/flexiplex/assets/10264291/260eb132-5b3e-43cb-a9d8-61276e4f3aba)
![Figure_2](https://github.com/DavidsonGroup/flexiplex/assets/10264291/e28e5c58-2dc2-4b9e-8536-abcdd77dc9b0)

**Comment by nadiadavidson** [comment]
It switched the order of the images on upload, so first image with this custom upper limit and second the default.

**Comment by olliecheng** [comment]
At the moment the default lower bound is the 0.95 quantile ([code](https://github.com/DavidsonGroup/flexiplex/blob/main/scripts/flexiplex_filter/main.py#L29-L36)). Admittedly I just eyeballed this value because it looks 'about right' with my sample datasets, but it seems to be a bit too strict at times.

A couple of alternative ideas
* BLAZE uses the value of the 0.95 quantile, divided by 20
* BLAZE also includes a 'high sensitivity' setting which uses c0.95 divided by 200. Might be good to include such a flag for those stubborn datasets as an easy fix
* A possibly more reliable approach could look for this region, which tends to indicate a breakdown of read quality. These are indicated by regions with hundreds/thousands of reads which all have the same, low count (usually something like <1).
  <img width="93" alt="image" src="https://github.com/DavidsonGroup/flexiplex/assets/20185977/0229e143-dd18-4eba-b5bf-042cb2c54fe5">

What do you think?
