### ISSUE TITLE
Processing time

### ISSUE THREAD

**Issue by nrhorner** [DavidsonGroup/flexiplex#40]
Hi,

I'm trying to run some 10x reads though flexiplex, but it's taking quite a long time to process. 1,000 reads took 17mins.
I'm using flexiplex v1.0.1 on Ubuntu 20.04

This is the commend used:
```flexiplex -d 10x3v3 -k 3M-february-2018.txt -p 32 1k_test.fq```

3M-february-2018.txt is the 3Prime v3 whitelist from 10x

Maybe I'm doing something wrong?

Thanks,

Neil

**Comment by nadiadavidson** [comment]
Hi Neil,

It's taking so long because the whitelist from 10x is very large. If you don't know the cell barcodes (non-empty drops) from matched single cell data, you can discvoer these first from the data, using the instructions at: https://davidsongroup.github.io/flexiplex/#assigning-long-reads-to-10x-barcodes-when-barcodes-are-unknown 
This should be much fasters. Please let us know if you run into any other issues.

Cheers,
Nadia.

**Comment by nrhorner** [comment]
Hi Nadia,

Thanks for the info. I will try the two phase solution as suggested.

Cheers,

Neil
